import "~/styles/globals.css";

import { Inter } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import Sidebar from "./_components/layout/Sidebar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Astoria Community Chest</title>
        <meta name="description" content="Astoria Community Chest" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={`font-sans ${inter.variable}`}>
        <TRPCReactProvider>
          <main className="to-aqua-10 flex h-full flex-col bg-gradient-to-b from-aqua-950 sm:flex-row">
            <MobileLogo />
            <Sidebar />
            <div className="to-aqua-10 flex min-h-screen w-full flex-col items-center justify-center overflow-scroll bg-gradient-to-b from-aqua-950 p-5 text-white">
              {children}
            </div>
          </main>
        </TRPCReactProvider>
      </body>
    </html>
  );
}

const MobileLogo = () => (
  <>
    <div className="fixed z-50 h-24 w-full border-b-2 border-slate-900 bg-gradient-to-b from-aqua-800 to-aqua-950 pt-5 sm:hidden ">
      <h1 className="mb-2 text-center text-3xl text-white">Community Chest</h1>
    </div>
    <div className="h-24 sm:hidden " />
  </>
);
